# Source: 2048-app/templates/2048-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: "app-2048"
  name: "app-2048"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: "app-2048"
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: "app-2048"
    spec:
      containers:
        - args:
            - nginx
            - -g
            - daemon off;
          env:
            - name: LOGLEVEL
              value: INFO
            - name: API_KEY
              value: key-456
            - name: ENVIRONMENT
              value: dev
            - name: AZURE_API_KEY
              value: "{{ .Values.env.AZURE_API_KEY }}"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: app-secrets
                    key: MYSQL_ROOT_PASSWORD
          envFrom:
            - secretRef:
                name: app-secrets
          image: jagdev/2048:24.4.0
          name: "app-2048"
          ports:
            - containerPort: 80
              protocol: TCP
      hostname: "2048"
      restartPolicy: Always
