deployment:
    image: "jagdev/2048"
    tag: "24.4.0"
name: app-2048
env:
    LOG_LEVEL: "INFO"
    API_KEY: "key-456"
    AZURE_API_KEY: <+secrets.getValue("AZURE_API_KEY")>
    MYSQL_ROOT_PASSWORD: <+secrets.getValue("MYSQL_ROOT_PASSWORD")>
    MYSQL_USER: "jagdev"
    MYSQL_USER_PASSWORD: "pass123"
    RUN_ENV: <+pipeline.variables.get("RUN_ENV")>

serviceAccount:
    create: true
cloudAccountId: <+pipeline.variables.get("CLOUD_ACCOUNT_ID")>
clusterName: <+pipeline.variables.get("CLUSTER_NAME")>

