apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: "{{ .Values.name }}"
  name: "{{ .Values.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: "{{ .Values.name }}"
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: "{{ .Values.name }}"
    spec:
      containers:
        - args:
            - nginx
            - -g
            - daemon off;
          env:
            - name: LOGLEVEL
              value: {{ .Values.env.LOG_LEVEL }}
            - name: API_KEY
              value: {{ .Values.env.API_KEY }}
            - name: RUN_ENV
              value: {{ .Values.env.RUN_ENV }}
            - name: AZURE_API_KEY
              value: {{ .Values.env.AZURE_API_KEY }}
          envFrom:
            - secretRef:
                name: {{ .Values.name }}-env-secret
          image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
          name: "{{ .Values.name }}"
          ports:
            - containerPort: 80
              protocol: TCP
      hostname: "2048"
      restartPolicy: Always
