apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-env-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.env.MYSQL_ROOT_PASSWORD | b64enc }}
  MYSQL_USER: {{ .Values.env.MYSQL_USER | b64enc }}
  MYSQL_USER_PASSWORD: {{ .Values.env.MYSQL_USER_PASSWORD | b64enc }}
